// Code generated by entc, DO NOT EDIT.

package movie

const (
	// Label holds the string label denoting the movie type in the database.
	Label = "movie"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// EdgeDirector holds the string denoting the director edge name in mutations.
	EdgeDirector = "director"
	// EdgeReview holds the string denoting the review edge name in mutations.
	EdgeReview = "review"
	// Table holds the table name of the movie in the database.
	Table = "movies"
	// DirectorTable is the table that holds the director relation/edge.
	DirectorTable = "movies"
	// DirectorInverseTable is the table name for the Director entity.
	// It exists in this package in order to avoid circular dependency with the "director" package.
	DirectorInverseTable = "directors"
	// DirectorColumn is the table column denoting the director relation/edge.
	DirectorColumn = "director_movies"
	// ReviewTable is the table that holds the review relation/edge. The primary key declared below.
	ReviewTable = "review_movies"
	// ReviewInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewInverseTable = "reviews"
)

// Columns holds all SQL columns for movie fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldRank,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "movies"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"director_movies",
}

var (
	// ReviewPrimaryKey and ReviewColumn2 are the table columns denoting the
	// primary key for the review relation (M2M).
	ReviewPrimaryKey = []string{"review_id", "movie_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
